FROM eclipse-temurin:11-jre-alpine
RUN mkdir -p /opt/app/reports
RUN mkdir reports
COPY ./target/<%= dasherizedBaseName %>-<%= projectVersion %>.jar /opt/app
USER root
RUN chown root:root /opt/app/<%= dasherizedBaseName %>-<%= projectVersion %>.jar
EXPOSE <%= serverPort %>
CMD ["java", "-Dspring.profiles.active=docker,api-docs", "-jar", "/opt/app/<%= dasherizedBaseName %>-<%= projectVersion %>.jar"]
#CMD ["java", "-Dspring.profiles.active=mysql", "-jar", "/opt/app/cimsreporting-0.0.1-SNAPSHOT.jar"]